version: '2'
services:
   ipfs-node:
     image: ipfs/go-ipfs
     container_name: "ipfs-node-private"
     ports:
       - 4001:4001
       - 5001:5001
     volumes:
       - ./ipfs-node:/data/ipfs/
   cluster:
     image: ipfs/ipfs-cluster:latest
     container_name: "ipfs-cluster-private"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-node/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
       IPFS_BOOTSTRAP_RM_ALL: "true"
     ports:
       - 9094:9094
       - 9095:9095
       - 9096:9096
     depends_on:
       - ipfs-node
     volumes:
       - ./cluster:/data/ipfs-cluster
