version: '3'
services:
   node:
    image: ipfs/go-ipfs:latest
    container_name: "storagechain"
    environment:
      - IBP2P_FORCE_PNET=1
      - IPFS_LOGGING=debug
      - MONITORINGINTERVAL="5s"
    ports:
      # - 80:80
      - 4001:4001
      - 5001:5001
      - 8080:8080
      # - 443:443 #optional
    volumes:
      - ./swarm.key:/data/ipfs/swarm.key
      - ./storage/ipfs:/data/ipfs/
      - ./script.sh:/script.sh
    entrypoint: sh -c "/script.sh"
    # restart: unless-stopped
   cluster:
     image: ipfs/ipfs-cluster:latest
     entrypoint: sh -c "/follower.sh"
     environment:
       CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/node/tcp/5001
       CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
       CLUSTER_MONITORINGINTERVAL: "5s"
       CLUSTER_PEERNAME: $CLUSTER_NAME
       CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster

     ports:
       - 9094:9094
       - 9095:9095
       - 9096:9096
     depends_on:
       - node
     volumes:
       - ./storage/cluster:/data/ipfs-cluster
       - ./follower.sh:/follower.sh
   file-server:
    container_name: "storagechain-server"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
     - 3008:3008

