version: '3'

services:

   node:
    image: ipfs/go-ipfs
    container_name: "storagechain"
    environment:
      - IBP2P_FORCE_PNET=1
      - IPFS_LOGGING=debug
      - MONITORINGINTERVAL="5s"
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ./swarm.key:/data/ipfs/swarm.key
      - ./storage/ipfs:/data/ipfs/
      - ./script.sh:/script.sh
    entrypoint: sh -c "/script.sh"
    restart: unless-stopped

   file-server:
    image: storagechain/cluster-file-server:latest
    environment:
      ENV: "production"
      PORT: 3008
      API_SERVER_URL: "https://storagechain-be.invo.zone/api"
    ports:
     - 3008:3008
    platform: linux/amd64
    restart: unless-stopped

