version: '3'

services:

   file-server:
    image: storagechain/cluster-file-server:latest
    environment:
      ENV: "production"
      PORT: 3008
    ports:
     - 3008:3008
    platform: linux/amd64
    restart: unless-stopped

